### ISSUE TITLE
core: nil pointer dereference in /build-transaction

### ISSUE THREAD

**Issue by jbowens** [chain/chain#489]
I noticed this error when failing over between two cored processes with high transaction throughput. Shortly after the secondary becomes leader, these nil pointer dereferences happen. A little while later, all build-transaction calls succeed. It doesn't always happen on a failover. It seems like it's probably a race condition surrounding some leader-only state (maybe the state tree?).

I wish we reported a stack trace of where the panic was.

```
app=cored buildtag=dev processID=chain-mba.local-28703-d06d338b073853927021 reqid=c9adf2bf2996e67cc980 at=http.go:52 t=2017-02-08T01:33:48.007350845Z subreqid=782d7ec96a950d4a654f status=500 chaincode=CH000 path=/build-transaction error="runtime error: invalid memory address or nil pointer dereference"
app=cored buildtag=dev processID=chain-mba.local-28703-d06d338b073853927021 reqid=f47f7464280f03e67a68 at=http.go:52 t=2017-02-08T01:33:48.014702926Z subreqid=3d069c6bd5ea0fdd782e status=500 chaincode=CH000 path=/build-transaction error="runtime error: invalid memory address or nil pointer dereference"
```

**Comment by jbowens** [comment]
Looks like it is the state tree. I instrumented my local core to get this stack trace:

```
app=cored buildtag=dev processID=chain-mba.local-48683-335a274c1f2354d0c795 reqid=77c3f4d7dc89682ad008 at=http.go:79 t=2017-02-08T21:44:47.274730631Z subreqid=d69026ff95ec8a68a9df 0x12f6e10="runtime error: invalid memory address or nil pointer dereference"
goroutine 8923 [running]:
runtime/debug.Stack(0x16ce4a0, 0x16c73a0, 0x4204840)
	/usr/local/go/src/runtime/debug/stack.go:24 +0x79
chain/core.batchRecover(0x41d7f20, 0xc4300a70b0, 0xc4300ac460)
	/Users/jackson/src/chain/core/http.go:68 +0x391
panic(0x16c73a0, 0x4204840)
	/usr/local/go/src/runtime/panic.go:489 +0x2cf
chain/core/account.(*reserver).checkUTXO(0xc4200184e0, 0xc434279180, 0xc42ffcf2e0)
	/Users/jackson/src/chain/core/account/reserve.go:234 +0x5a
chain/core/account.(*reserver).(chain/core/account.checkUTXO)-fm(0xc434279180, 0xc4237984e0)
	/Users/jackson/src/chain/core/account/reserve.go:249 +0x34
chain/core/account.(*sourceReserver).reserveFromCache(0xc42ffc3b90, 0x1c, 0x448a, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
	/Users/jackson/src/chain/core/account/reserve.go:304 +0x251
chain/core/account.(*sourceReserver).reserve(0xc42ffc3b90, 0x41d7f20, 0xc4300a70b0, 0x1c, 0x448a, 0xc4237b34a0, 0x10, 0xc42ffc3b90, 0xc423f48ba8, 0xc423f48b38, ...)
	/Users/jackson/src/chain/core/account/reserve.go:284 +0x102
chain/core/account.(*reserver).reserve(0xc4200184e0, 0x41d7f20, 0xc4300a70b0, 0xc862728768761fcc, 0x87ef07a53c1f42b3, 0xac9b3a53c0ea01ed, 0x91ad2889d08b5131, 0xc4237b34a0, 0x10, 0x448a, ...)
	/Users/jackson/src/chain/core/account/reserve.go:119 +0xff
chain/core/account.(*reserver).Reserve.func1(0xc420018508, 0xc428e0e000, 0xc42ffcf5a0, 0xc423f48ca0)
	/Users/jackson/src/chain/core/account/reserve.go:109 +0xba
chain/sync/idempotency.(*Group).Once(0xc420018508, 0xc4237b4cc0, 0x24, 0xc42ffcf648, 0xc42a227cc0, 0xc420030801, 0xc423ea2c60, 0x167f800)
	/Users/jackson/src/chain/sync/idempotency/group.go:58 +0x142
chain/core/account.(*reserver).Reserve(0xc4200184e0, 0x41d7f20, 0xc4300a70b0, 0xc862728768761fcc, 0x87ef07a53c1f42b3, 0xac9b3a53c0ea01ed, 0x91ad2889d08b5131, 0xc4237b34a0, 0x10, 0x448a, ...)
	/Users/jackson/src/chain/core/account/reserve.go:110 +0x146
chain/core/account.(*spendAction).Build(0xc429dd7ec0, 0x41d7f20, 0xc4300a70b0, 0xc4236f6680, 0x0, 0x0)
	/Users/jackson/src/chain/core/account/builder.go:62 +0x292
chain/core/txbuilder.Build(0x41d7f20, 0xc4300a70b0, 0x0, 0xc423791d80, 0x4, 0x4, 0xed02d888b, 0xcc0965d, 0x42162e0, 0x0, ...)
	/Users/jackson/src/chain/core/txbuilder/txbuilder.go:40 +0x162
chain/core.(*Handler).buildSingle(0xc420216000, 0x41d7f20, 0xc4300a70b0, 0xc4300a6ed0, 0xc4300ac460, 0xc4300a70b0, 0xc42190ff90)
	/Users/jackson/src/chain/core/transact.go:56 +0x7e3
chain/core.(*Handler).build.func1(0x41d7f20, 0xc4300a6ea0, 0xc4300ac470, 0xc4300ac460, 0x1, 0x1, 0xc420216000, 0xc4300a1a60, 0x1, 0x4, ...)
	/Users/jackson/src/chain/core/transact.go:92 +0x142
created by chain/core.(*Handler).build
	/Users/jackson/src/chain/core/transact.go:98 +0x15c
```

Going to try to add collection of stack traces for recovered panics before I fix this particular panic.

**Comment by jbowens** [comment]
This error happens if the new leader is processing a build request but has not yet finished executing `protocol.Recover`. The account reserver tries to access the state tree [here](https://github.com/chain/chain/blob/main/core/account/reserve.go#L233), but `s.Tree` is nil.

I think the correct solution is to adapt the `core/leader` package so that when a core becomes leader, it synchronously runs the `leader.Run` closure. Then [`leader.IsLeading`](https://github.com/chain/chain/blob/main/core/leader/leader.go#L22) should return false until the `leader.Run` closure completes. In [`cmd/cored`](https://github.com/chain/chain/blob/main/cmd/cored/main.go#L373-L385), we can adapt the `leader.Run` closure to do blockchain recovery synchronously, and then spawn goroutines for things that can be asynchronous.

Any thoughts?
